FROM node:16-alpine
USER node

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

#packge.json files is being copied into workdir(means /app
COPY --chown=node:node ./package.json ./ 
RUN npm install

#all files into our project copied into workdir(app)
COPY --chown=node:node ./ ./ 

CMD ["npm","start"]